export const GRAPH = {
  NODE_COUNT: 100,

  NODE_RADIUS: 2,

  MIN_DISTANCE: 0.06,

  MAX_CONNECTIONS: 3,

  CENTER_HOLE_WIDTH: 0.42,
  CENTER_HOLE_HEIGHT: 0.34,

  ANIMATION_SPEED_MIN: 0.2,
  ANIMATION_SPEED_MAX: 0.6,

  BREATHING_AMPLITUDE: 4,

  EDGE_OPACITY: 0.15,

  EDGE_WIDTH: 1,

  NODE_COLOR: "#0F7EA8",

  BACKGROUND: "#FCFCFA",
} as const;